name: Pikafish

on:
  push:
    branches:
      - ruler

jobs:
  Pikafish-x86-64:
    name: ${{ matrix.config.name }}${{ matrix.arch }}
    runs-on: ${{ matrix.config.os }}
    env:
      ARCH: x86-64${{ matrix.arch }}
      COMPCXX: clang++
      COMP: clang
      EXE: pikafish${{ matrix.arch }}${{ matrix.config.ext }}
      LLVM_VERSION: 20
    strategy:
      matrix:
        config:
        
          - name: Windows
            os: windows-latest
            shell: msys2 {0}
            ext: .exe
        arch: [ "-avx512bw", "-avx512", "-bmi2", "-avx2", "-sse41-popcnt", "-ssse3"]
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}

    steps:
      - uses: actions/checkout@v4

     

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang make git

      - name: Compile ${{ matrix.arch }} build
        run: |
          make -j build EXE=$EXE
          make strip EXE=$EXE
          cp $EXE ../

      # Artifacts automatically get zipped.
      # To avoid double-zipping, we use the unzipped directory
      - uses: actions/upload-artifact@v4
        with:	
          name: Pikafish-${{ matrix.config.name }}${{ matrix.arch }}
          path: ${{ env.EXE }}

 

    

  Pikafish:
    name: Pikafish
    runs-on: ubuntu-latest
    needs: [Pikafish-x86-64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
      
      - name: Put binaries into OS-specific directories
        run: |
          mkdir Windows
          mv Pikafish-Windows*/* Windows
        
        
      - name: Download wiki
        run: |
          git clone https://github.com/official-pikafish/Pikafish.wiki.git Wiki
          cd Wiki
          rm -rf .git

      # Artifacts automatically get zipped.
      # To avoid double-zipping, we use the unzipped directory
      - uses: actions/upload-artifact@v4
        with:
          name: Pikafish
          path: |
            Windows
            Wiki
            AUTHORS
            CONTRIBUTING.md
            Copying.txt
            README.md
            Top CPU Contributors.txt
